### ISSUE TITLE
記事が書けない

### ISSUE THREAD

**Issue by cutls** [GenbuHase/ArticleEditor#7]
roorのapp.jsの141行目と152行目の
`req.body.id`
は、コードを詳しく読んだわけではありませんが定義されてないように思えます。
これを
`id`
としたところエラーを返すことがなくなりました。
正しい対処かどうかわからないですが確認お願いします。

**Comment by GenbuHase** [comment]
@cutls 様
Issueありがとうございます。コードの不具合確認いたしました。
出来るだけ早急にv1.2.0をリリースし、これを修正版とさせて頂きます。

ありがとうございました。
